quarkus:
    test:
        continuous-testing: DISABLED
    # 开发阶段关闭 dev-service 服务
    devservices:
        enabled: false
    # mongodb 配置
    mongodb:
        connection-string: mongodb://pc.zxj:27017
        database: hamster
    # 日志配置
    log:
        category:
            "org.mongodb.driver":
                level: DEBUG
    # 索引依赖
    index-dependency:
        "rs-api":
            group-id: jakarta.ws.rs
            artifact-id: jakarta.ws.rs-api
